export interface SustainabilityQuestions {
    energyReductionGoal: boolean,
    energyReductionPercent: number,
    energyReductionBaselineYear: number,
    energyReductionTargetYear: number,
    energyIsAbsolute: boolean,
    greenhouseReductionGoal: boolean,
    greenhouseReductionPercent: number,
    greenhouseReductionBaselineYear: number,
    greenhouseReductionTargetYear: number,
    greenhouseIsAbsolute: boolean,
    renewableEnergyGoal: boolean,
    renewableEnergyPercent: number,
    renewableEnergyBaselineYear: number,
    renewableEnergyTargetYear: number,
    wasteReductionGoal: boolean,
    wasteReductionPercent: number,
    wasteReductionBaselineYear: number,
    wasteReductionTargetYear: number,
    wasteIsAbsolute: boolean,
    waterReductionGoal: boolean,
    waterReductionPercent: number,
    waterReductionBaselineYear: number,
    waterReductionTargetYear: number,
    waterIsAbsolute: boolean
  }