// This file can be replaced during build by using the `fileReplacements` array.
// `ng build --prod` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.
import packageInfo from '../../package.json';
export const environment = {
  production: false,
  version: packageInfo.version
};

export const globalVariables = {
  months: [
    { name: 'January', abbreviation: 'Jan', monthNumValue: 0 },
    { name: 'February', abbreviation: 'Feb', monthNumValue: 1 },
    { name: 'March', abbreviation: 'Mar', monthNumValue: 2 },
    { name: 'April', abbreviation: 'Apr', monthNumValue: 3 },
    { name: 'May', abbreviation: 'May', monthNumValue: 4 },
    { name: 'June', abbreviation: 'Jun', monthNumValue: 5 },
    { name: 'July', abbreviation: 'Jul', monthNumValue: 6 },
    { name: 'August', abbreviation: 'Aug', monthNumValue: 7 },
    { name: 'September', abbreviation: 'Sept', monthNumValue: 8 },
    { name: 'October', abbreviation: 'Oct', monthNumValue: 9 },
    { name: 'November', abbreviation: 'Nov', monthNumValue: 10 },
    { name: 'December', abbreviation: 'Dec', monthNumValue: 11 }
  ],

  states: [
    { name: 'ALABAMA', abbreviation: 'AL' },
    { name: 'ALASKA', abbreviation: 'AK' },
    { name: 'AMERICAN SAMOA', abbreviation: 'AS' },
    { name: 'ARIZONA', abbreviation: 'AZ' },
    { name: 'ARKANSAS', abbreviation: 'AR' },
    { name: 'CALIFORNIA', abbreviation: 'CA' },
    { name: 'COLORADO', abbreviation: 'CO' },
    { name: 'CONNECTICUT', abbreviation: 'CT' },
    { name: 'DELAWARE', abbreviation: 'DE' },
    { name: 'DISTRICT OF COLUMBIA', abbreviation: 'DC' },
    { name: 'FEDERATED STATES OF MICRONESIA', abbreviation: 'FM' },
    { name: 'FLORIDA', abbreviation: 'FL' },
    { name: 'GEORGIA', abbreviation: 'GA' },
    { name: 'GUAM', abbreviation: 'GU' },
    { name: 'HAWAII', abbreviation: 'HI' },
    { name: 'IDAHO', abbreviation: 'ID' },
    { name: 'ILLINOIS', abbreviation: 'IL' },
    { name: 'INDIANA', abbreviation: 'IN' },
    { name: 'IOWA', abbreviation: 'IA' },
    { name: 'KANSAS', abbreviation: 'KS' },
    { name: 'KENTUCKY', abbreviation: 'KY' },
    { name: 'LOUISIANA', abbreviation: 'LA' },
    { name: 'MAINE', abbreviation: 'ME' },
    { name: 'MARSHALL ISLANDS', abbreviation: 'MH' },
    { name: 'MARYLAND', abbreviation: 'MD' },
    { name: 'MASSACHUSETTS', abbreviation: 'MA' },
    { name: 'MICHIGAN', abbreviation: 'MI' },
    { name: 'MINNESOTA', abbreviation: 'MN' },
    { name: 'MISSISSIPPI', abbreviation: 'MS' },
    { name: 'MISSOURI', abbreviation: 'MO' },
    { name: 'MONTANA', abbreviation: 'MT' },
    { name: 'NEBRASKA', abbreviation: 'NE' },
    { name: 'NEVADA', abbreviation: 'NV' },
    { name: 'NEW HAMPSHIRE', abbreviation: 'NH' },
    { name: 'NEW JERSEY', abbreviation: 'NJ' },
    { name: 'NEW MEXICO', abbreviation: 'NM' },
    { name: 'NEW YORK', abbreviation: 'NY' },
    { name: 'NORTH CAROLINA', abbreviation: 'NC' },
    { name: 'NORTH DAKOTA', abbreviation: 'ND' },
    { name: 'NORTHERN MARIANA ISLANDS', abbreviation: 'MP' },
    { name: 'OHIO', abbreviation: 'OH' },
    { name: 'OKLAHOMA', abbreviation: 'OK' },
    { name: 'OREGON', abbreviation: 'OR' },
    { name: 'PALAU', abbreviation: 'PW' },
    { name: 'PENNSYLVANIA', abbreviation: 'PA' },
    { name: 'PUERTO RICO', abbreviation: 'PR' },
    { name: 'RHODE ISLAND', abbreviation: 'RI' },
    { name: 'SOUTH CAROLINA', abbreviation: 'SC' },
    { name: 'SOUTH DAKOTA', abbreviation: 'SD' },
    { name: 'TENNESSEE', abbreviation: 'TN' },
    { name: 'TEXAS', abbreviation: 'TX' },
    { name: 'UTAH', abbreviation: 'UT' },
    { name: 'VERMONT', abbreviation: 'VT' },
    { name: 'VIRGIN ISLANDS', abbreviation: 'VI' },
    { name: 'VIRGINIA', abbreviation: 'VA' },
    { name: 'WASHINGTON', abbreviation: 'WA' },
    { name: 'WEST VIRGINIA', abbreviation: 'WV' },
    { name: 'WISCONSIN', abbreviation: 'WI' },
    { name: 'WYOMING', abbreviation: 'WY' }
  ],
  naicsCodes: [
    { code: 311 - 339, industyType: 'All Manufacturing Industries' },
    { code: 311, industyType: 'Food' },
    { code: 3112, industyType: 'Grain And Oilseed Milling' },
    { code: 311221, industyType: 'Wet Corn Milling' },
    { code: 31131, industyType: 'Sugar' },
    { code: 3114, industyType: 'Fruit And Vegetable Preserving And Specialty Foods' },
    { code: 3115, industyType: 'Dairy Products' },
    { code: 3116, industyType: 'Animal Slaughtering And Processing' },
    { code: 312, industyType: 'Beverage And Tobacco Products' },
    { code: 3121, industyType: 'Beverages' },
    { code: 3122, industyType: 'Tobacco' },
    { code: 313, industyType: 'Textile Mills' },
    { code: 314, industyType: 'Textile Product Mills' },
    { code: 315, industyType: 'Apparel' },
    { code: 316, industyType: 'Leather And Allied Products' },
    { code: 321, industyType: 'Wood Products' },
    { code: 321113, industyType: 'Sawmills' },
    { code: 3212, industyType: 'Veneer, Plywood, And Engineered Woods' },
    { code: 321219, industyType: 'Reconstituted Wood Products' },
    { code: 3219, industyType: 'Other Wood Products' },
    { code: 322, industyType: 'Paper' },
    { code: 322110, industyType: 'Pulp Mills' },
    { code: 322121, industyType: 'Paper Mills, Except Newsprint' },
    { code: 322122, industyType: 'Newsprint Mills' },
    { code: 322130, industyType: 'Paperboard Mills' },
    { code: 323, industyType: 'Printing And Related Support' },
    { code: 324, industyType: 'Petroleum And Coal Products' },
    { code: 324110, industyType: 'Petroleum Refineries' },
    { code: 324121, industyType: 'Asphalt Paving Mixture And Block' },
    { code: 324122, industyType: 'Asphalt Shingle And Coating Materials' },
    { code: 324199, industyType: 'Other Petroleum And Coal Products' },
    { code: 325, industyType: 'Chemicals' },
    { code: 325110, industyType: 'Petrochemicals' },
    { code: 325120, industyType: 'Industrial Gases' },
    { code: 325180, industyType: 'Other Basic Inorganic Chemicals' },
    { code: 325193, industyType: 'Ethyl Alcohol' },
    { code: 325194, industyType: 'Cyclic Crudes, Intermediate And Gum And Wood Chemicals' },
    { code: 325199, industyType: 'Other Basic Organic Chemicals' },
    { code: 325211, industyType: 'Plastics Materials And Resins' },
    { code: 325212, industyType: 'Synthetic Rubber' },
    { code: 325220, industyType: 'Artificial And Synthetic Fibers And Filaments' },
    { code: 325311, industyType: 'Nitrogenous Fertilizers' },
    { code: 325312, industyType: 'Phosphatic Fertilizers' },
    { code: 3254, industyType: 'Pharmaceuticals And Medicines' },
    { code: 325412, industyType: 'Pharmaceutical Preparation' },
    { code: 325992, industyType: 'Photographic Film, Paper, Plate, And Chemicals' },
    { code: 326, industyType: 'Plastics And Rubber Products' },
    { code: 327, industyType: 'Nonmetallic Mineral Products' },
    { code: 327120, industyType: 'Clay Building Material And Refractories' },
    { code: 327211, industyType: 'Flat Glass' },
    { code: 327212, industyType: 'Other Pressed And Blown Glass And Glassware' },
    { code: 327213, industyType: 'Glass Containers' },
    { code: 327215, industyType: 'Glass Products From Purchased Glass' },
    { code: 327310, industyType: 'Cements' },
    { code: 327410, industyType: 'Lime' },
    { code: 327420, industyType: 'Gypsum' },
    { code: 327993, industyType: 'Mineral Wool' },
    { code: 331, industyType: 'Primary Metals' },
    { code: 331110, industyType: 'Iron And Steel Mills And Ferroalloys' },
    { code: 3312, industyType: 'Steel Products From Purchased Steel' },
    { code: 3313, industyType: 'Alumina And Aluminum' },
    { code: 331314, industyType: 'Secondary Smelting And Alloying Of Aluminum' },
    { code: 331315, industyType: 'Aluminum Sheet, Plate And Foils' },
    { code: 331318, industyType: 'Other Aluminum Rolling, Drawing And Extruding' },
    { code: 3314, industyType: 'Nonferrous Metals, Except Aluminum' },
    { code: 331410, industyType: 'Nonferrous Metal (Except Aluminum) Smelting And Refining' },
    { code: 3315, industyType: 'Foundries' },
    { code: 331511, industyType: 'Iron Foundries' },
    { code: 331523, industyType: 'Nonferrous Metal Die-Casting Foundries' },
    { code: 331524, industyType: 'Aluminum Foundries, Except Die-Casting' },
    { code: 332, industyType: 'Fabricated Metal Products' },
    { code: 333, industyType: 'Machinery' },
    { code: 334, industyType: 'Computer And Electronic Products' },
    { code: 334413, industyType: 'Semiconductors And Related Devices' },
    { code: 335, industyType: 'Elec. Equip., Appliances, Components' },
    { code: 336, industyType: 'Transportation Equipment' },
    { code: 336111, industyType: 'Automobiles' },
    { code: 336112, industyType: 'Light Trucks And Utility Vehicles' },
    { code: 3364, industyType: 'Aerospace Products' },
    { code: 336411, industyType: 'Aircraft' },
    { code: 337, industyType: 'Furniture And Related Products' },
    { code: 339, industyType: 'Miscellaneous' }
  ]
}
/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/dist/zone-error';  // Included with Angular CLI.
