name: CI/CD
on:
  push:
    branches:
      - 'master'
  workflow_dispatch:
    
jobs:
  web:
    uses: ./.github/workflows/web.yml

  electron:
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    uses: ./.github/workflows/electron.yml
